# -*- coding: utf-8 -*-
"""формирование реквизитов в pdf

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/162vdTB5iMivCG-joCAqRHSgHXAMjrNQJ
"""

!pip install translate

!pip install fpdf2

from fpdf import FPDF
from translate import Translator

def translating(words):
    translator=Translator(from_lang='ru',to_lang='en')
    end_text=translator.translate(words)
    return end_text
def create_bank_statement(table_of_history):
    for i in list(table_of_history.columns.values):
        table_of_history[i]=table_of_history[i].apply(translating)
    pdf=FPDF('P','mm','letter')
    pdf.add_page()
    pdf.set_font('helvetica','',16)
    pdf.cell(40,10,table_of_history.iloc[0][3],ln=True)
    for i in range(table_of_history.shape[0]):
        pdf.cell(40,10,table_of_history.iloc[i][0]+' '+table_of_history.iloc[i][1]+' '+table_of_history.iloc[i][2]+' '+table_of_history.iloc[i][3],ln=True)
    pdf.output('bank-statement.pdf')